---
abstract: 'create a HTTP::Request from a curl command line'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  HTTP::CookieJar: '0'
  HTTP::CookieJar::LWP: '0'
  HTTP::Tiny: '0'
  IO::Socket::SSL: '0'
  LWP::UserAgent: '0'
  Path::Tiny: '0'
  Test2::V0: '0'
  Test::HTTP::LocalServer: '0.67'
  WWW::Mechanize: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Request-FromCurl
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  File::Basename: '0'
  Filter::signatures: '0.16'
  Getopt::Long: '2.39'
  HTTP::Request: '6.07'
  HTTP::Request::Common: '6.07'
  HTTP::Request::Generator: '0.09'
  JSON: '0'
  List::Util: '1.29'
  MIME::Base64: '0'
  Moo: '2'
  PerlX::Maybe: '0'
  URI: '0'
  URI::Escape: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/Corion/HTTP-Request-FromCurl/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/HTTP-Request-FromCurl.git
version: '0.52'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
